/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as CountriesIndexRouteImport } from './routes/countries.index'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as EmployerPostRouteImport } from './routes/employer.post'
import { Route as EmployerJobsRouteImport } from './routes/employer.jobs'
import { Route as EmployerApplicationsRouteImport } from './routes/employer.applications'
import { Route as DashboardSavedRouteImport } from './routes/dashboard.saved'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardCvRouteImport } from './routes/dashboard.cv'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard.applications'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as JobsSlugApplyRouteImport } from './routes/jobs.$slug_.apply'
import { Route as JobBoardIndustrySlugRouteImport } from './routes/job-board.industry.$slug'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerPostRoute = EmployerPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerJobsRoute = EmployerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerApplicationsRoute = EmployerApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => EmployerRoute,
} as any)
const DashboardSavedRoute = DashboardSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCvRoute = DashboardCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/countries/$slug',
  path: '/countries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugApplyRoute = JobsSlugApplyRouteImport.update({
  id: '/jobs/$slug_/apply',
  path: '/jobs/$slug/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const JobBoardIndustrySlugRoute = JobBoardIndustrySlugRouteImport.update({
  id: '/job-board/industry/$slug',
  path: '/job-board/industry/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employer': typeof EmployerRouteWithChildren
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/training': typeof TrainingRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/cv': typeof DashboardCvRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/employer/post': typeof EmployerPostRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/countries/': typeof CountriesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/job-board/industry/$slug': typeof JobBoardIndustrySlugRoute
  '/jobs/$slug/apply': typeof JobsSlugApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employer': typeof EmployerRouteWithChildren
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/training': typeof TrainingRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/cv': typeof DashboardCvRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/employer/post': typeof EmployerPostRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/countries': typeof CountriesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/job-board/industry/$slug': typeof JobBoardIndustrySlugRoute
  '/jobs/$slug/apply': typeof JobsSlugApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employer': typeof EmployerRouteWithChildren
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/training': typeof TrainingRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/cv': typeof DashboardCvRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/employer/post': typeof EmployerPostRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/countries/': typeof CountriesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/job-board/industry/$slug': typeof JobBoardIndustrySlugRoute
  '/jobs/$slug_/apply': typeof JobsSlugApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/companies'
    | '/contact'
    | '/dashboard'
    | '/employer'
    | '/industries'
    | '/login'
    | '/training'
    | '/countries/$slug'
    | '/dashboard/applications'
    | '/dashboard/cv'
    | '/dashboard/profile'
    | '/dashboard/saved'
    | '/employer/applications'
    | '/employer/jobs'
    | '/employer/post'
    | '/jobs/$slug'
    | '/countries/'
    | '/jobs/'
    | '/job-board/industry/$slug'
    | '/jobs/$slug/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/companies'
    | '/contact'
    | '/dashboard'
    | '/employer'
    | '/industries'
    | '/login'
    | '/training'
    | '/countries/$slug'
    | '/dashboard/applications'
    | '/dashboard/cv'
    | '/dashboard/profile'
    | '/dashboard/saved'
    | '/employer/applications'
    | '/employer/jobs'
    | '/employer/post'
    | '/jobs/$slug'
    | '/countries'
    | '/jobs'
    | '/job-board/industry/$slug'
    | '/jobs/$slug/apply'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/companies'
    | '/contact'
    | '/dashboard'
    | '/employer'
    | '/industries'
    | '/login'
    | '/training'
    | '/countries/$slug'
    | '/dashboard/applications'
    | '/dashboard/cv'
    | '/dashboard/profile'
    | '/dashboard/saved'
    | '/employer/applications'
    | '/employer/jobs'
    | '/employer/post'
    | '/jobs/$slug'
    | '/countries/'
    | '/jobs/'
    | '/job-board/industry/$slug'
    | '/jobs/$slug_/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmployerRoute: typeof EmployerRouteWithChildren
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  TrainingRoute: typeof TrainingRoute
  CountriesSlugRoute: typeof CountriesSlugRoute
  JobsSlugRoute: typeof JobsSlugRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  JobBoardIndustrySlugRoute: typeof JobBoardIndustrySlugRoute
  JobsSlugApplyRoute: typeof JobsSlugApplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/post': {
      id: '/employer/post'
      path: '/post'
      fullPath: '/employer/post'
      preLoaderRoute: typeof EmployerPostRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/jobs': {
      id: '/employer/jobs'
      path: '/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof EmployerJobsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/applications': {
      id: '/employer/applications'
      path: '/applications'
      fullPath: '/employer/applications'
      preLoaderRoute: typeof EmployerApplicationsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/dashboard/saved': {
      id: '/dashboard/saved'
      path: '/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof DashboardSavedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cv': {
      id: '/dashboard/cv'
      path: '/cv'
      fullPath: '/dashboard/cv'
      preLoaderRoute: typeof DashboardCvRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/countries/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug_/apply': {
      id: '/jobs/$slug_/apply'
      path: '/jobs/$slug/apply'
      fullPath: '/jobs/$slug/apply'
      preLoaderRoute: typeof JobsSlugApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-board/industry/$slug': {
      id: '/job-board/industry/$slug'
      path: '/job-board/industry/$slug'
      fullPath: '/job-board/industry/$slug'
      preLoaderRoute: typeof JobBoardIndustrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardCvRoute: typeof DashboardCvRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSavedRoute: typeof DashboardSavedRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardCvRoute: DashboardCvRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSavedRoute: DashboardSavedRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EmployerRouteChildren {
  EmployerApplicationsRoute: typeof EmployerApplicationsRoute
  EmployerJobsRoute: typeof EmployerJobsRoute
  EmployerPostRoute: typeof EmployerPostRoute
}

const EmployerRouteChildren: EmployerRouteChildren = {
  EmployerApplicationsRoute: EmployerApplicationsRoute,
  EmployerJobsRoute: EmployerJobsRoute,
  EmployerPostRoute: EmployerPostRoute,
}

const EmployerRouteWithChildren = EmployerRoute._addFileChildren(
  EmployerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  CompaniesRoute: CompaniesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmployerRoute: EmployerRouteWithChildren,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  TrainingRoute: TrainingRoute,
  CountriesSlugRoute: CountriesSlugRoute,
  JobsSlugRoute: JobsSlugRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  JobBoardIndustrySlugRoute: JobBoardIndustrySlugRoute,
  JobsSlugApplyRoute: JobsSlugApplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
